# Generated by Django 5.2.7 on 2025-11-09 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('value_num', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('value_text', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['key', 'measured_at'], name='main_dashbo_key_6d3519_idx')],
            },
        ),
    ]
