# Generated by Django 5.2.7 on 2025-11-09 16:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardmetric',
            name='delta_num',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dashboardmetric',
            name='measured_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddIndex(
            model_name='dashboardmetric',
            index=models.Index(fields=['-measured_at'], name='main_dashbo_measure_e372ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='dashboardmetric',
            constraint=models.UniqueConstraint(fields=('key', 'measured_at'), name='uniq_key_measured_at'),
        ),
    ]
