# Generated by Django 5.2.7 on 2025-11-09 16:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='last_message_preview',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='message',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='citations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='model_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_completion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_prompt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='tool_calls',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('system', 'system'), ('tool', 'tool')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='chat_messag_convers_3154fc_idx'),
        ),
    ]
