# Generated by Django 5.2.7 on 2025-11-12 06:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatconversation_last_message_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='chatconversation',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='비로그인 사용자를 위한 세션 키', max_length=40),
        ),
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='last_message_preview',
            field=models.CharField(blank=True, help_text='목록에서 보여줄 마지막 메시지 요약', max_length=140),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='slug',
            field=models.SlugField(editable=False, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='chatconversation',
            name='title',
            field=models.CharField(blank=True, default='새로운 대화', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System'), ('tool', 'Tool')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['session_key', 'created_at'], name='chat_chatco_session_ed215a_idx'),
        ),
    ]
